import { PrimaryGeneratedColumn, BaseEntity as TypeOrmBaseEntity } from 'typeorm';

/**
 * BaseEntity is a simple JavaBean domain object with an `id` property.
 * It is used as a base class for other entities that require an identifier.
 */
export abstract class BaseEntity extends TypeOrmBaseEntity {
  /**
   * The unique identifier for the entity.
   * Auto-generated primary key using database's identity strategy.
   * @example 1
   */
  @PrimaryGeneratedColumn()
  id?: number; // Optional as it's generated by the database

  /**
   * Checks if the entity is new (i.e., has not yet been persisted and assigned an ID).
   * @returns `true` if the ID is null, indicating a new entity; otherwise, `false`.
   */
  isNew(): boolean {
    return this.id === null || this.id === undefined;
  }
}
