import { PrimaryGeneratedColumn, BaseEntity as TypeOrmBaseEntity } from 'typeorm';

/**
 * @module Common
 * @description
 * Simple base class for domain objects that have an auto-generated ID.
 * This entity serves as the foundation for other entities needing an ID.
 * It also includes a helper method `isNew()` to check if the entity has been persisted yet.
 */
export abstract class BaseEntity extends TypeOrmBaseEntity {
  /**
   * The unique identifier for the entity.
   * Auto-generated by the database.
   */
  @PrimaryGeneratedColumn()
  id?: number; // Using 'number' for integer IDs

  /**
   * Checks if this entity is new (i.e., has not yet been persisted to the database).
   * An entity is considered new if its `id` property is `null` or `undefined`.
   *
   * @returns {boolean} `true` if the entity is new, `false` otherwise.
   */
  isNew(): boolean {
    return this.id === null || this.id === undefined;
  }
}
