/**
 * @module models/BaseEntity
 * @description Defines the base entity class with a primary key,
 *              mimicking Spring's `BaseEntity.java`.
 */

import { PrimaryGeneratedColumn, BaseEntity as TypeOrmBaseEntity } from 'typeorm';

/**
 * @class BaseEntity
 * @extends {TypeOrmBaseEntity}
 * @description Simple JavaBean domain object with an `id` property.
 *              Used as a base class for objects needing this property.
 */
export abstract class BaseEntity extends TypeOrmBaseEntity {
  /**
   * @property {number | undefined} id
   * @description The unique identifier for the entity.
   *              Automatically generated by the database.
   */
  @PrimaryGeneratedColumn()
  id?: number;

  /**
   * @method isNew
   * @description Checks if the entity is new (i.e., has not been persisted to the database yet).
   * @returns {boolean} `true` if the ID is null or undefined, `false` otherwise.
   */
  isNew(): boolean {
    return this.id === null || this.id === undefined;
  }
}
