-- Schema for the PostgreSQL PetClinic database
-- This script contains DDL statements to create tables and indices.
-- It uses `IF NOT EXISTS` to ensure idempotency.

-- Create vets table
CREATE TABLE IF NOT EXISTS vets (
  id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Auto-incrementing primary key
  first_name TEXT, -- TEXT type for first name
  last_name  TEXT  -- TEXT type for last name
);
CREATE INDEX IF NOT EXISTS vets_last_name_idx ON vets (last_name); -- Index on last name for efficient lookups

-- Create specialties table
CREATE TABLE IF NOT EXISTS specialties (
  id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Auto-incrementing primary key
  name TEXT -- TEXT type for specialty name
);
CREATE INDEX IF NOT EXISTS specialties_name_idx ON specialties (name); -- Index on name for efficient lookups

-- Create vet_specialties junction table for many-to-many relationship
CREATE TABLE IF NOT EXISTS vet_specialties (
  vet_id       INT NOT NULL REFERENCES vets (id), -- Foreign key to vets table
  specialty_id INT NOT NULL REFERENCES specialties (id), -- Foreign key to specialties table
  UNIQUE (vet_id, specialty_id) -- Ensures unique pairs of vet and specialty
);
-- No explicit index needed on individual foreign keys if combined unique index is present and covers them.
-- If vet_id or specialty_id are frequently queried individually, separate indexes might be beneficial.

-- Create types table (for pet types like cat, dog, etc.)
CREATE TABLE IF NOT EXISTS types (
  id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Auto-incrementing primary key
  name TEXT -- TEXT type for pet type name
);
CREATE INDEX IF NOT EXISTS types_name_idx ON types (name); -- Index on name for efficient lookups

-- Create owners table
CREATE TABLE IF NOT EXISTS owners (
  id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Auto-incrementing primary key
  first_name TEXT, -- TEXT type for first name
  last_name  TEXT, -- TEXT type for last name
  address    TEXT, -- TEXT type for address
  city       TEXT, -- TEXT type for city
  telephone  TEXT  -- TEXT type for telephone
);
CREATE INDEX IF NOT EXISTS owners_last_name_idx ON owners (last_name); -- Index on last name for efficient lookups

-- Create pets table
CREATE TABLE IF NOT EXISTS pets (
  id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Auto-incrementing primary key
  name       TEXT, -- TEXT type for pet name
  birth_date DATE, -- DATE type for birth date
  type_id    INT NOT NULL REFERENCES types (id) ON DELETE RESTRICT, -- Foreign key to types table, restrict deletion of type if pets exist
  owner_id   INT REFERENCES owners (id) ON DELETE CASCADE -- Foreign key to owners table, cascade deletion of pets if owner is deleted
);
CREATE INDEX IF NOT EXISTS pets_name_idx ON pets (name); -- Index on name
CREATE INDEX IF NOT EXISTS pets_owner_id_idx ON pets (owner_id); -- Index on owner_id for efficient lookups by owner

-- Create visits table
CREATE TABLE IF NOT EXISTS visits (
  id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Auto-incrementing primary key
  pet_id      INT REFERENCES pets (id) ON DELETE CASCADE, -- Foreign key to pets table, cascade deletion of visits if pet is deleted
  visit_date  DATE, -- DATE type for visit date
  description TEXT  -- TEXT type for visit description
);
CREATE INDEX IF NOT EXISTS visits_pet_id_idx ON visits (pet_id); -- Index on pet_id for efficient lookups by pet
