-- PostgreSQL specific SQL statements for creating the database schema.
-- Uses `CREATE TABLE IF NOT EXISTS` and `GENERATED BY DEFAULT AS IDENTITY` for IDs.

CREATE TABLE IF NOT EXISTS vets (
  id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name TEXT,
  last_name  TEXT
);
CREATE INDEX IF NOT EXISTS vets_last_name_idx ON vets (last_name);

CREATE TABLE IF NOT EXISTS specialties (
  id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT
);
CREATE INDEX IF NOT EXISTS specialties_name_idx ON specialties (name);

CREATE TABLE IF NOT EXISTS vet_specialties (
  vet_id       INT NOT NULL REFERENCES vets (id) ON DELETE CASCADE,
  specialty_id INT NOT NULL REFERENCES specialties (id) ON DELETE CASCADE,
  UNIQUE (vet_id, specialty_id)
);

CREATE TABLE IF NOT EXISTS types (
  id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT
);
CREATE INDEX IF NOT EXISTS types_name_idx ON types (name);

CREATE TABLE IF NOT EXISTS owners (
  id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name TEXT,
  last_name  TEXT, -- PostgreSQL performs case-insensitive comparisons for LIKE by default
  address    TEXT,
  city       TEXT,
  telephone  TEXT
);
CREATE INDEX IF NOT EXISTS owners_last_name_idx ON owners (last_name);

CREATE TABLE IF NOT EXISTS pets (
  id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       TEXT,
  birth_date DATE,
  type_id    INT NOT NULL REFERENCES types (id),
  owner_id   INT REFERENCES owners (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS pets_name_idx ON pets (name);
CREATE INDEX IF NOT EXISTS pets_owner_id_idx ON pets (owner_id);

CREATE TABLE IF NOT EXISTS visits (
  id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pet_id      INT REFERENCES pets (id) ON DELETE CASCADE,
  visit_date  DATE,
  description TEXT
);
CREATE INDEX IF NOT EXISTS visits_pet_id_idx ON visits (pet_id);
