/**
 * @fileoverview Defines the Product model structure.
 * This file serves as a blueprint for product data, primarily for type checking
 * and understanding the expected shape of product objects in our application.
 * In a more complex application with a real database (e.g., MongoDB with Mongoose,
 * or SQL with Sequelize), this file would contain the schema definition
 * and potentially static/instance methods for database interactions.
 * For this simple in-memory example, it primarily documents the data structure.
 */

/**
 * @class Product
 * @description Represents a product entity in the application.
 * This class provides a constructor to create new product instances.
 */
class Product {
  /**
   * Creates an instance of Product.
   * @param {string} name - The name of the product.
   * @param {string} description - A detailed description of the product.
   * @param {number} price - The price of the product.
   * @param {string} [id] - Optional. A unique identifier for the product.
   *                        Typically generated by the data store (e.g., db.js).
   * @param {Date} [createdAt] - Optional. The timestamp when the product was created.
   *                             Typically generated by the data store (e.g., db.js).
   */
  constructor(name, description, price, id = null, createdAt = null) {
    // Validate inputs (simple validation for demonstration)
    if (!name || typeof name !== 'string' || name.trim() === '') {
      throw new Error('Product name is required and must be a non-empty string.');
    }
    if (!description || typeof description !== 'string' || description.trim() === '') {
      throw new Error('Product description is required and must be a non-empty string.');
    }
    if (typeof price !== 'number' || price < 0) {
      throw new Error('Product price is required and must be a non-negative number.');
    }

    /**
     * @property {string|null} id - Unique identifier for the product. Null if not yet persisted.
     */
    this.id = id;

    /**
     * @property {string} name - The name of the product.
     */
    this.name = name.trim();

    /**
     * @property {string} description - The description of the product.
     */
    this.description = description.trim();

    /**
     * @property {number} price - The price of the product.
     */
    this.price = price;

    /**
     * @property {Date|null} createdAt - The timestamp when the product was created. Null if not yet persisted.
     */
    this.createdAt = createdAt;
  }

  /**
   * Returns a plain object representation of the product.
   * Useful when passing data to the database layer or rendering in views.
   * @returns {object} A plain object with product properties.
   */
  toObject() {
    return {
      id: this.id,
      name: this.name,
      description: this.description,
      price: this.price,
      createdAt: this.createdAt
    };
  }
}

// Export the Product class so it can be used in other modules.
module.exports = Product;
